// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8BOVBBzSuRE6XBG_9_oAOwG84oAp5Qnc',
    appId: '1:1060149520292:web:8ab1420f025497debec331',
    messagingSenderId: '1060149520292',
    projectId: 'ksbdatatech-a01c9',
    authDomain: 'ksbdatatech-a01c9.firebaseapp.com',
    databaseURL: 'https://ksbdatatech-a01c9-default-rtdb.firebaseio.com',
    storageBucket: 'ksbdatatech-a01c9.appspot.com',
    measurementId: 'G-W12WVFM0N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyC7bLaM6VbzXSC7Ay9hOyiG2lZmSwH3bnk',
      appId: '11:640943854017:web:4ebfa25c6fd77c86cf1f40',
      messagingSenderId: '640943854017',
      projectId: 'jimmyxchange-a4c43',
      databaseURL:
          'https://jimmyxchange-a4c43-default-rtdb.asia-southeast1.firebasedatabase.app',
      storageBucket: 'jimmyxchange-a4c43.appspot.com',
      measurementId: "G-7Q14DYTEPW");

// const firebaseConfig = {
//   apiKey: "AIzaSyC7bLaM6VbzXSC7Ay9hOyiG2lZmSwH3bnk",
//   authDomain: "jimmyxchange-a4c43.firebaseapp.com",
//   databaseURL: "https://jimmyxchange-a4c43-default-rtdb.asia-southeast1.firebasedatabase.app",
//   projectId: "jimmyxchange-a4c43",
//   storageBucket: "jimmyxchange-a4c43.appspot.com",
//   messagingSenderId: "640943854017",
//   appId: "1:640943854017:web:4ebfa25c6fd77c86cf1f40",
//   measurementId: "G-7Q14DYTEPW"
// };

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7lkZAF5P4LOzD_JODDQ6MSWaWKTOCFTU',
    appId: '1:1060149520292:ios:a15d4b10e0ca18bbbec331',
    messagingSenderId: '1060149520292',
    projectId: 'ksbdatatech-a01c9',
    databaseURL: 'https://ksbdatatech-a01c9-default-rtdb.firebaseio.com',
    storageBucket: 'ksbdatatech-a01c9.appspot.com',
    androidClientId:
        '1060149520292-3t3slhcmt9cll9omehqbjcmo384di04j.apps.googleusercontent.com',
    iosClientId:
        '1060149520292-5r5a5lhcb0vrrk3vh1fdua03370lkic5.apps.googleusercontent.com',
    iosBundleId: 'com.app.ksbdatatech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7lkZAF5P4LOzD_JODDQ6MSWaWKTOCFTU',
    appId: '1:1060149520292:ios:9b664435c90c4681bec331',
    messagingSenderId: '1060149520292',
    projectId: 'ksbdatatech-a01c9',
    databaseURL: 'https://ksbdatatech-a01c9-default-rtdb.firebaseio.com',
    storageBucket: 'ksbdatatech-a01c9.appspot.com',
    androidClientId:
        '1060149520292-3t3slhcmt9cll9omehqbjcmo384di04j.apps.googleusercontent.com',
    iosClientId:
        '1060149520292-4eml7e0sdkdaase025k116t7haph72lm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ksbTech',
  );
}
